image: harbor.meta42.indc.vnet.com/sameersbn/docker:latest

stages:
  - package
  - docker_build
  - deploy_k8s

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.cache/.m2/repository"  # Maven 本地仓库
  DOCKER_AUTH_CONFIG: '{"auths":{"harbor.meta42.indc.vnet.com": {"auth": "emhlbnRpYW54aWFuZzpUaWFuMTgzMzI4MjUzMDku"}}}'

# 缓存配置，使用 MinIO 缓存 Maven 本地仓库和构建文件
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/.m2/repository  # Maven 依赖缓存路径
    - .cache/jar  # 存储构建的 JAR 包

mvn_build_job:
  image: harbor.meta42.indc.vnet.com/sameersbn/maven-aliyun-mirror:3.6.2-jdk-14
  stage: package
  tags:
    - TEST-K8S-CLUSTER
  script:
    - mvn clean install
    - JAR_NAME=$(ls target/*.jar | grep -v "original" | head -n 1)  # 动态获取 JAR 文件名
    - mkdir -p .cache/jar  # 确保缓存目录存在
    - cp $JAR_NAME .cache/jar/
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .cache/.m2/repository  # Maven 依赖缓存路径
      - .cache/jar  # 缓存 JAR 文件
    policy: pull-push  # 确保缓存被推送

docker_build_job:
  image: harbor.meta42.indc.vnet.com/sameersbn/docker:latest
  stage: docker_build
  tags:
    - TEST-K8S-CLUSTER
  script:
    - mkdir -p .cache/jar  # 确保缓存目录存在
    - JAR_NAME=$(ls .cache/jar/*.jar | head -n 1)  # 从缓存中动态获取 JAR 文件名
    - mkdir target
    - cp $JAR_NAME target/  # 复制 JAR 文件
    - mkdir ~/.docker/
    - echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
    - cat ~/.docker/config.json
    - TAG_NAME="${CI_COMMIT_REF_NAME}-$(date +%Y%m%d%H%M)-${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}"
    - echo $TAG_NAME > tag_name.txt  # 将 TAG_NAME 写入文件
    - docker build -t $REGISTRY_URL/library/helloworld:$TAG_NAME .
    - docker push $REGISTRY_URL/library/helloworld:$TAG_NAME
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .cache/jar  # 确保 JAR 文件在构建阶段可用
    policy: pull  # 确保缓存被拉取用于构建
  artifacts:
    paths:
      - tag_name.txt  # 保存 TAG_NAME 文件供后续 Job 使用

deploy_k8s_job:
  image: harbor.meta42.indc.vnet.com/sameersbn/kubectl:v1.23.0
  stage: deploy_k8s
  tags:
    - TEST-K8S-CLUSTER
  dependencies:
    - docker_build_job  # 确保 artifacts 从 docker_build_job 中拉取
  script:
    - mkdir ~/.kube/
    - echo $kube_config | base64 -d > ~/.kube/config
    - TAG_NAME=$(cat tag_name.txt)  # 从 artifacts 中读取 TAG_NAME
    - echo $TAG_NAME
    - cat ~/.kube/config
    - |-
      cat <<EOF | kubectl apply -f -
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: helloworld
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: helloworld
        template:
          metadata:
            labels:
              app: helloworld
          spec:
            imagePullSecrets:
              - name: harbor-registry-secret
            containers:
            - name: helloworld
              image: $REGISTRY_URL/library/helloworld:$TAG_NAME
              imagePullPolicy: Always
              ports:
              - containerPort: 8080
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: helloworld
      spec:
        ports:
        - port: 80
          targetPort: 8080
          nodePort: 31280
          name: helloworld
        selector:
          app: helloworld
        type: NodePort
      EOF
