apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: gitlab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
      - name: helloworld
        image: $REGISTRY_URL/library/helloworld:$TAG_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: gitlab
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32180
    name: helloworld
  selector:
    app: helloworld
  type: NodePort
